# Generated by Django 5.2.6 on 2025-09-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Musicas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("artist", models.CharField(max_length=100, verbose_name="Artista")),
                ("album", models.CharField(max_length=100, verbose_name="Album")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("BRC", "BREAKCORE"),
                            ("POP", "POP"),
                            ("JPOP", "J-POP"),
                            ("RCK", "ROCK"),
                            ("JRCK", "J-ROCK"),
                            ("MTL", "METAL"),
                            ("JMTL", "J-METAL"),
                            ("RAP", "RAP"),
                            ("JRAP", "J-RAP"),
                            ("CLSC", "Classica"),
                            ("MPB", "Musica Popular Brasileira"),
                        ],
                        max_length=100,
                        verbose_name="Genero",
                    ),
                ),
                ("releaseDate", models.DateField()),
            ],
            options={
                "verbose_name": "Musica",
                "verbose_name_plural": "Musicas",
            },
        ),
    ]
